

name: armTemplateDeployment


on:
  push:
    branches:
       -main
  workflow_dispatch:


jobs:
  
  armDeploy:
   
    runs-on: ubuntu-latest

    
    steps:
      
      - uses: actions/checkout@v3
      - name: Azure Login
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy Resource Group rg-githubactions
        uses: Azure/arm-deploy@v1
        with:
          scope: subcription
          subscriptionId: c454cdac-7e10-4194-9431-6fda95d467bd
          region: Australia East
          template: ./arm-templates/resourcegroup.jsom
          deploymentName: rg-githubactions


      
      

           
        